version: '3.8'

services:
  learningbase:
    image: krish6447/learningbase_flower-classification:latest
    container_name: flower_learningbase
    volumes:
      - ai_system:/tmp
    command: ["sh", "-c", "echo 'Learning Base Container Started' && ls -la /tmp/learningBase/ && tail -f /dev/null"]
    networks:
      - flower_network

  activationbase:
    image: krish6447/activationbase_flower-classification:latest
    container_name: flower_activationbase
    volumes:
      - ai_system:/tmp
    command: ["sh", "-c", "echo 'Activation Base Container Started' && ls -la /tmp/activationBase/ && tail -f /dev/null"]
    networks:
      - flower_network

volumes:
  ai_system:
    external: true

networks:
  flower_network:
    driver: bridge